# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SqlAlerts < Formula
  desc "Get notifications about new rows in your database"
  homepage "https://github.com/yendefrr/sql-alerts"
  version "1.6.1"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yendefrr/sql-alerts/releases/download/1.6.1/sql-alerts_Darwin_x86_64.tar.gz"
      sha256 "10aab6f11a2449fa7747ec9aaaa420998083ad311443dc0989903e6664bbc4ad"

      def install
        bin.install "sql-alerts" => "sqlal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yendefrr/sql-alerts/releases/download/1.6.1/sql-alerts_Darwin_arm64.tar.gz"
      sha256 "974ba3785e7a99661d8f5b9a829a0ada3e3d09bdb79a0cf67f7ed4a7a7883825"

      def install
        bin.install "sql-alerts" => "sqlal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yendefrr/sql-alerts/releases/download/1.6.1/sql-alerts_Linux_x86_64.tar.gz"
      sha256 "747606998e0f6bf40cb1e31e434e933958d3ecdca7f792e6d17b1b1a54713fe5"

      def install
        bin.install "sql-alerts" => "sqlal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yendefrr/sql-alerts/releases/download/1.6.1/sql-alerts_Linux_arm64.tar.gz"
      sha256 "ef9a820f1b426499875fcc99d46e376a9ea132102cb1d4e16df3a53e0f15259f"

      def install
        bin.install "sql-alerts" => "sqlal"
      end
    end
  end
end
