# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SqlAlerts < Formula
  desc "Get notifications about new rows in your database"
  homepage "https://github.com/yendefrr/sql-alerts"
  version "1.3.1"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yendefrr/sql-alerts/releases/download/1.3.1/sql-alerts_Darwin_x86_64.tar.gz"
      sha256 "c235f25e30e86ffa760296fdca8129e3a0f6c495890bc074ef2aa8ccf9b7c35e"

      def install
        bin.install "sql-alerts" => "sqlal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yendefrr/sql-alerts/releases/download/1.3.1/sql-alerts_Darwin_arm64.tar.gz"
      sha256 "216db8e8a5d3d6b8b78b2322d2b4c8ca0c9b311db14d83a7af0dd9300d662fd1"

      def install
        bin.install "sql-alerts" => "sqlal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yendefrr/sql-alerts/releases/download/1.3.1/sql-alerts_Linux_x86_64.tar.gz"
      sha256 "9541278659dc180ae6e192ebe4ff5b40fb13f62829cd16d941b1794f222bed06"

      def install
        bin.install "sql-alerts" => "sqlal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yendefrr/sql-alerts/releases/download/1.3.1/sql-alerts_Linux_arm64.tar.gz"
      sha256 "d00731a11eb31860cc4e821a435c0bbee42060f27eb0768c780dc0eb77a67173"

      def install
        bin.install "sql-alerts" => "sqlal"
      end
    end
  end
end
